# Generated by Django 3.2.6 on 2022-05-12 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='hematology_first_rack_one',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=200)),
                ('css_of_position', models.CharField(max_length=500)),
                ('tube_type', models.IntegerField()),
                ('accession_number', models.CharField(max_length=10)),
            ],
        ),
    ]
