# Generated by Django 3.2.6 on 2022-05-12 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20220512_1226'),
    ]

    operations = [
        migrations.AddField(
            model_name='hematology_first_rack_one',
            name='sorting_purposes',
            field=models.IntegerField(default=0),
        ),
    ]
