# Generated by Django 3.2.6 on 2022-05-13 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_patient_information'),
    ]

    operations = [
        migrations.CreateModel(
            name='chemistry_first_rack_one',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(blank=True, max_length=200)),
                ('css_of_position', models.CharField(blank=True, max_length=500)),
                ('tube_type', models.CharField(blank=True, max_length=500)),
                ('accession_number', models.CharField(blank=True, max_length=10)),
            ],
            options={
                'verbose_name': 'Hematology First Rack One',
                'verbose_name_plural': 'Hematology First Rack One',
            },
        ),
        migrations.AlterModelOptions(
            name='patient_information',
            options={'verbose_name': 'Patient Information', 'verbose_name_plural': 'Patient Information'},
        ),
    ]
