# Generated by Django 3.2.6 on 2022-05-13 23:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20220512_2056'),
    ]

    operations = [
        migrations.AddField(
            model_name='chemistry_first_rack_one',
            name='mrn',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.patient_information', unique=True),
        ),
        migrations.AddField(
            model_name='hematology_first_rack_one',
            name='mrn',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.patient_information', unique=True),
        ),
    ]
