# Generated by Django 3.2.6 on 2022-05-16 21:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20220513_1956'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chemistry_first_rack_one',
            name='mrn',
        ),
        migrations.RemoveField(
            model_name='hematology_first_rack_one',
            name='mrn',
        ),
        migrations.RemoveField(
            model_name='patient_information',
            name='patient_accession_number',
        ),
        migrations.CreateModel(
            name='accession_number',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accession_number', models.CharField(blank=True, max_length=200)),
                ('patient_link', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='home.patient_information')),
            ],
        ),
    ]
