# Generated by Django 3.2.6 on 2022-05-16 22:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20220516_1755'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accession_number',
            options={'verbose_name': 'Accession Number', 'verbose_name_plural': 'Accession Number'},
        ),
        migrations.AlterField(
            model_name='accession_number',
            name='patient_link',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.patient_information'),
        ),
    ]
