# Generated by Django 3.2.6 on 2022-05-16 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20220516_1800'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='accession_number',
            new_name='accession_numbers',
        ),
    ]
