# Generated by Django 3.2.6 on 2022-05-16 22:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_rename_accession_number_accession_numbers'),
    ]

    operations = [
        migrations.AddField(
            model_name='hematology_first_rack_one',
            name='accession_number_link',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.accession_numbers'),
        ),
    ]
