# Generated by Django 3.2.6 on 2022-05-16 22:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_hematology_first_rack_one_accession_number_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hematology_first_rack_one',
            name='accession_number',
        ),
        migrations.AlterField(
            model_name='hematology_first_rack_one',
            name='accession_number_link',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.accession_numbers'),
        ),
    ]
