# Generated by Django 3.2.6 on 2022-05-24 22:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_auto_20220524_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hematology_first_rack_one',
            name='test',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.accession_numbers'),
        ),
    ]
