# Generated by Django 3.2.6 on 2022-05-24 22:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_alter_hematology_first_rack_one_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hematology_first_rack_one',
            name='test',
        ),
        migrations.AddField(
            model_name='hematology_first_rack_one',
            name='rack_link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.accession_numbers'),
        ),
    ]
