# Generated by Django 3.2.6 on 2022-05-25 23:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_auto_20220524_1909'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accession_numbers',
            name='rack_link',
        ),
        migrations.AddField(
            model_name='hematology_first_rack_one',
            name='accession_link',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.accession_numbers'),
        ),
    ]
