# Generated by Django 3.2.6 on 2022-07-14 22:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_alter_hematology_first_rack_one_accession_link'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chemistry_first_rack_one',
            options={'verbose_name': 'Chemistry First Rack One', 'verbose_name_plural': 'Chemistry First Rack One'},
        ),
        migrations.RemoveField(
            model_name='chemistry_first_rack_one',
            name='accession_number',
        ),
        migrations.AddField(
            model_name='chemistry_first_rack_one',
            name='accession_link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.accession_numbers'),
        ),
    ]
