# Generated by Django 3.2.6 on 2022-07-16 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_auto_20220714_1830'),
    ]

    operations = [
        migrations.AddField(
            model_name='chemistry_first_rack_one',
            name='rack_name',
            field=models.CharField(default='Chemistry First Rack One', max_length=200),
        ),
        migrations.AddField(
            model_name='hematology_first_rack_one',
            name='rack_name',
            field=models.CharField(default='Hematology First Rack One', max_length=200),
        ),
    ]
