# Generated by Django 3.2.6 on 2022-07-16 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_auto_20220715_2002'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chemistry_first_rack_one',
            name='rack_name',
        ),
        migrations.RemoveField(
            model_name='hematology_first_rack_one',
            name='rack_name',
        ),
    ]
