# Generated by Django 3.2.6 on 2022-07-16 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_auto_20220715_2006'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chemistry_first_rack_one',
            options={'verbose_name': 'Chemistry First Shift R Rack #1', 'verbose_name_plural': 'Chemistry First Shift R Rack #1'},
        ),
        migrations.AlterModelOptions(
            name='hematology_first_rack_one',
            options={'verbose_name': 'Hematology First Shift R Rack #1', 'verbose_name_plural': 'Hematology First Shift R Rack #1'},
        ),
        migrations.AddField(
            model_name='hematology_first_rack_one',
            name='name_of_tubetype',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
